### ISSUE TITLE
Orion Framework general to-do list

### ISSUE THREAD

**Issue by tylerjwatson** [NyxStudios/Orion#21]
The below contains a list of general items to be completed in the Orion Framework
- [x] Assembly patcher in OTAPIv2
- [x] OTAPI v2 Release to NuGet
- [x] Orion: Project skeleton
- [x] Orion: Injector framework, Service and plugin bases
- [ ] Orion: Service interface definitions/documentation
- [ ] Orion: Built-in service implementations
  - [ ] Service: AAA Service (#31)
  - [ ] Service: Command service (#32)
  - [ ] Service: Inventory Service
  - [ ] Service: REST framework
  - [ ] Service: Data/Database service

**Comment by kevzhao2** [comment]
Closing as outdated.
