### ISSUE TITLE
Orion v1.4 Development Progress

### ISSUE THREAD

**Issue by kevzhao2** [NyxStudios/Orion#55]
This issue will serve as a tracker for Orion progress (under the v1.4 branch). It will also indicate how "ready" Orion is in terms of developing against it. A large portion of the pre-development milestones have been knocked out, which means that it is pretty much okay to start developing against Orion.

The concurrent development milestones can be completed at the same time as developing against Orion, as it involves supplementing Orion with missing packet definitions, event definitions, etc.

Pre-development will be done mostly directly onto the v1.4 branch. Once there is enough developer bandwidth (besides me), we can begin migrating to a better workflow involving new branches and pull requests.

## Pre-Development Milestones

- [x] Service and plugin architecture
  - [x] Binding and rebinding services
  - [x] Binding `ILogger` and `Lazy<T>`
  - [x] Loading and "unloading" plugins
- [x] Event architecture
  - [x] Priority-based event handlers
  - [x] Auto-ignoring canceled events
  - [x] Logging
  - [x] Aggregated events and event handlers under `OrionKernel`
- [x] Packet architecture
  - [x] Efficient `struct`-based packets
  - [x] Efficient `struct`-based modules
  - [x] Packet event handling in `OrionPlayerService`
- [x] Starting Terraria abstractions
  - [x] `IItem` and `IItemService`
  - [x] `INpc` and `INpcService`
  - [x] `IPlayer` and `IPlayerService`
  - [x] Projectile abstraction (#57)
  - [x] Tile abstraction (#58)
  - [x] World abstraction (#61)

## Concurrent Development Milestones

- [ ] Packet definitions (#65)
  - [ ] Module definitions (1 of 11 completed)
- [ ] Additional event definitions
- [ ] Augment Terraria abstractions
  - [x] Chest abstraction
  - [x] Sign abstraction
  - [ ] Tile entity abstraction
