### ISSUE TITLE
Orion v1.4 "Meta" Progress

### ISSUE THREAD

**Issue by kevzhao2** [NyxStudios/Orion#56]
This issue will serve as a tracker for "meta" Orion progress. Items that fall under this category include, but are not limited to, creating developer-oriented documentation so that other developers can begin contributing to Orion, lobbying for support behind Orion, etc.

- [x] Clean up the repository. There is a lot of outdated information.
- [x] Improve the README. This could even just link to the wiki.
- [x] Clean up and set up labels for issues in this repository.
- [x] Clean up and set up milestones in this repository.
- [x] Set up automated documentation generation (#59)
- [x] Create developer documentation for Orion. That way, we can start onboarding new developers to contribute to Orion. Some areas of contribution include:
  - Defining missing packets.
  - Defining missing modules.
  - Augmenting the current Terraria abstractions (such as adding stats to items, etc.)
- [ ] Write more comprehensive example plugins for Orion. The current example plugin on the wiki sidebar is a start, but we could write something which more explicitly shows the benefits of Orion. We might want to, e.g., provide an example of a service rebinding.
- [x] Clean up the contributor guidelines for Orion in the wiki.
- [ ] Attempt to rally support behind this.

More items to be added later as needed.
